Fix macOS build on GitHub Actions.
The macOS build is currently failing due to this error:

    Building CXX object src/fiends/CMakeFiles/fiends.dir/main.cpp.o
    error: unknown warning option '-Wno-unqualified-std-cast-call'; did you mean '-Wno-qualified-void-return-type'? [-Werror,-Wunknown-warning-option]

Attempt to get this working by dropping `-DWALL=ON` from the Cmake
generation step.

Also remove the build options `-DHOMEBREW_NCURSES` and
`-DHOMEBREW_NCURSES_PATH` from the macOS build since these were dropped
a while ago, and remove the "Packages" step that ran `brew`, now also
unneeded.